### ISSUE TITLE
Question on "Production app build step"

### ISSUE THREAD

**Issue by qthompson** [decker405/figwheel-react-native#4]
Firstly, so happy you are working on this! I’ve tried this out, and it works really well.

This is not an issue, more of a question.

You have got a "Production app build step" item left as a todo, and if I can get that working then I’m going to upgrade one of my own projects to use your approach soon.

I am interested in having a go at getting something working myself, but as I’m inexperienced with this I am not sure where to get started. Have you had any initial ideas on how you are planning on solving this step yet?

**Comment by decker405** [comment]
I would figure that it would just require a "minify" build step with :optimizations :advanced, and then use the React Native packager to bundle it with react-native bundle --minify. And use the main.js bundle that is output from that.

However, it seems to not be that easy. I've been messing with it for the past 30 minutes or so and am running into a bit of difficulty with some dependencies and a few other js errors. I'll look at it more tonight and hopefully I can get something working this weekend.

**Comment by tiensonqin** [comment]
Thanks for bring figwheel's power, it's really working very well.
I tried react-native bundle, and it shows just like what you said,
so, any progress there?

➜  figwheel-react-native git:(master) ✗ react-native bundle                 
Building package...
Unable to resolve module goog.debug.Error from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module goog.dom.NodeType from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module goog.string from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module goog.asserts from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module goog.string from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module goog.object from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module goog.array from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module goog.string.StringBuffer from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module cljs.core from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module cljs.core from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module cljs.core from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module goog.string from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module goog.string.StringBuffer from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module cljs.core from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.debug from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.interop from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module clojure.string from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module cljs.core from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.impl.util from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.debug from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module cljs.core from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module cljs.core from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.debug from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.interop from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.ratom from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.impl.util from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module clojure.string from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module cljs.core from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.impl.util from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.impl.batching from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.ratom from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.interop from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.debug from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module cljs.core from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.impl.util from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.impl.component from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.interop from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.ratom from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.impl.batching from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module clojure.string from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.debug from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module cljs.core from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.impl.util from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.impl.component from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.interop from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.ratom from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module cljsjs.react from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.impl.template from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.impl.batching from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.debug from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module cljs.core from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
Unable to resolve module reagent.core from /Users/tienson/codes/ios/figwheel-react-native/index.ios.js
transforming [========================================] 100% 313/313
Build complete
Successfully saved bundle to ios/main.jsbundle

**Comment by tiensonqin** [comment]
Actually, i find [ReagentNativeDemo](https://github.com/chendesheng/ReagentNativeDemo) bundle works fine.

**Comment by tiensonqin** [comment]
Both react native v0.14.2 and v0.13.0 not works, but I find (ReagentNativeDemo)[https://github.com/chendesheng/ReagentNativeDemo] works fine when optimizations 
set to *whitespace*.

**Comment by decker405** [comment]
Interesting. Are you using react-native bundle with that project or still using the packager? Does it work with optimizations set to :advanced?

**Comment by tiensonqin** [comment]
I'm using react-native bundle.
Actually make goog global, and treat the output js as common js module,
just as what chendesheng did, [you can look at the issue](https://github.com/chendesheng/ReagentNativeDemo/issues/1),
v0.13.0 works fine!

**Comment by decker405** [comment]
Awesome! What about v0.14.x?

**Comment by tiensonqin** [comment]
@mfikes helped me in the #cljsrn slack channel, for now advanced maybe is difficult, maybe you should talk to him.

**Comment by decker405** [comment]
Ok, cool. I'll check it out

**Comment by tiensonqin** [comment]
v0.14.2 with :whitespace optimization can't bundle, 
:simple could as last i check,
sorry about this, xcode is upgrading now, can't do things.

**Comment by decker405** [comment]
No worries. Good work! I'll see what I can get running tonight.

**Comment by tiensonqin** [comment]
Thanks for your hard work, looking forward this!

**Comment by tiensonqin** [comment]
I uploaded a demo repo, v0.14.2 works well with optimizations set to :simple, 
surprisely, no need to hack the `goog`, also react packager will do the bundle automatically!

Link: [react native demo](https://github.com/tiensonqin/issues).

**Comment by tiensonqin** [comment]
I build a release and it's running in the real iphone 6.

**Comment by decker405** [comment]
@qthompson: just as an update, you should be able to get this going now.

@tiensonqin: I cleaned up a bit and changed the code so that figwheel can live reload without "Debug in Chrome" being selected. [Check it out.](/decker405/figwheel-react-native/tree/inSimulatorReload) I'm also thinking about shimming some of figwheel's code and doing a simple HUD on the device, but we'll see when/if I get to that.

**Comment by tiensonqin** [comment]
@decker405 That's really cool, will check this soon!

**Comment by qthompson** [comment]
@decker405 Thanks! I tried this out last weekend and it worked really well. It’s great to be able to use figwheel & [cljs-devtools](https://github.com/binaryage/cljs-devtools) in Chrome for development, and then be able to package it up afterwards.

Thanks very much to you and @tiensonqin for looking into this.
